# Generated by Django 5.2.8 on 2025-11-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_status_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
