# Generated by Django 5.2.8 on 2025-11-27 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_featured_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured_product_image',
            new_name='cover_image',
        ),
    ]
