# Generated by Django 5.2.8 on 2025-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
