# Generated by Django 5.2.8 on 2025-12-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_best_selling_alter_cart_sub_total_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_arrivals',
            field=models.BooleanField(default=False),
        ),
    ]
