# Generated by Django 5.2.8 on 2025-12-18 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='store.orderitem'),
        ),
    ]
