# Generated by Django 5.2.8 on 2025-12-18 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_reviews_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='order_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reviewed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='store.orderitem'),
        ),
    ]
