# Generated by Django 5.2.8 on 2025-12-18 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_reviews_order_item_orderitem_reviewed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='item',
            new_name='order_item',
        ),
    ]
