# Generated by Django 5.2.8 on 2025-12-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆ (1/5)'), (2, '★★☆☆☆ (2/5)'), (3, '★★★☆☆ (3/5)'), (4, '★★★★☆ (4/5)'), (5, '★★★★★ (5/5)')], default=None),
        ),
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.TextField(null=True),
        ),
    ]
