# Generated by Django 5.2.8 on 2025-12-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_reviews_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reply',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
