# Generated by Django 5.2.8 on 2026-01-03 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_wishlist_product_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner',
            field=models.CharField(blank=True, choices=[('Banner 1', 'Banner 1'), ('Banner 2', 'Banner 2'), ('Banner 3', 'Banner 3')], max_length=50, null=True),
        ),
    ]
