# Generated by Django 5.2.8 on 2026-01-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.CharField(blank=True, choices=[('Banner 1', 'Banner 1'), ('Banner 2', 'Banner 2'), ('Banner 3', 'Banner 3'), ('Banner 4', 'Banner 4')], max_length=50, null=True),
        ),
    ]
