# Generated by Django 5.2.8 on 2026-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.CharField(blank=True, choices=[('Banner 1', 'Banner 1'), ('Banner 2', 'Banner 2'), ('Banner 3', 'Banner 3'), ('Banner 4', 'Banner 4'), ('Banner 5', 'Banner 5'), ('Banner 6', 'Banner 6')], max_length=50, null=True),
        ),
    ]
