# Generated by Django 5.2.8 on 2026-01-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_contact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_message',
            name='email',
        ),
    ]
