# Generated by Django 5.2.8 on 2026-01-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_contact_message_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
